### ISSUE TITLE
 DAG support

### ISSUE THREAD

**Issue by mrchypark** [alexellis/workflow-yaml-template#1]
Is workflow support DAG?

**Comment by alexellis** [comment]
The code is available in this repo if you would like to experiment with that?

Could you give a quick example of how you'd like your DAG to work?

**Comment by mrchypark** [comment]
I found this repo what I want https://github.com/s8sg/faas-flow.

Thank you for reply!

**Comment by alexellis** [comment]
I think we could support DAG and it'd be interesting to see how we could do it most simply. faas-flow is unofficial, but has many features. Check it out

**Comment by mrchypark** [comment]
Simple is the most important. 

I'll wait. Thank you. :)
